### PR TITLE
[#131] Annotate reserved vocabularies when importing into workspace

### LINKED ISSUE #131: Discoverability of assignments of workspaces and R/W vocabularies
Currently a vocabulary can be open in write mode only in single workspace, which is limiting. If a user creates a workspace and wants to edit a vocabulary which is already part of another workspace, he should be able to have that information at hand so that he can e.g. redirect his attention to the other workspace.

### PR DESCRIPTION
**Pull request by karelklima**
This PR tackles with the use case when the user tries to import a vocabulary that is already being used in another workspace.

What changed in the Import vocabulary dialog:
- vocabularies that are already used in another workspace have a warning icon attached
- if such vocabulary is clicked, the user sees in which workspace is the vocabulary edited and there is a button to go to that workspace

image

We still need to change the dialog so that it is not possible to import vocabularies for read only, but AFAIK that cannot be done just yet because of other technical dependencies.

Feedback welcome!

Resolves #131.

### CODE REVIEW

**Review by psiotwo — COMMENTED** [review]
lgtm. 

To increase usability we should be able to quickly point the user to the 'last editor' of the workspace - either putting it in the message, or having the label of the conflicting workspace clickable.

**Comment by karelklima** [comment]
> To increase usability we should be able to quickly point the user to the 'last editor' of the workspace - either putting it in the message, or having the label of the conflicting workspace clickable.

There is the big "Go to workspace" button that you can click to do just that - it opens the blocking workspace with the vocabulary that the user wants to edit.  But maybe it would be better to have the info message / workspace name clickable instead.

**Comment by psiotwo** [comment]
> > To increase usability we should be able to quickly point the user to the 'last editor' of the workspace - either putting it in the message, or having the label of the conflicting workspace clickable.
> 
> There is the big "Go to workspace" button that you can click to do just that - it opens the blocking workspace with the vocabulary that the user wants to edit. But maybe it would be better to have the info message / workspace name clickable instead.

Ah, I see, I missed it ... :-) 

Anyway, a clickable link would be better IMO (The less on the screen the better).

**Comment by karelklima** [comment]
> Anyway, a clickable link would be better IMO (The less on the screen the better).

Done! Thanks for the feedback.

**Review by psiotwo — APPROVED** [review]
lgtm

**Pull request merged**
