### PR TITLE
[#125] Forms and dialogs UX improvements

### LINKED ISSUE #125: Provide better UX when sending forms
MC should provide better UX for popup forms
- if a form is sent, the submit button should be disabled until the action completes
- the main button and cancel button should not be at the top of each other -> the cancel button should be replaced with a X icon on the top right

### PR DESCRIPTION
**Pull request by karelklima**
Done:
- all the user actions / buttons in dialogs now give user immediate feedback, including progress indication
- some dialogs have auto-focused inputs
- dropped common "Cancel" button in favor of a cross icon on the top right of each dialog
- refactoring of common components (Dialog, FormDialog) and loading state / suspense mechanism

Notes:
- the dialog to add a new vocabulary to workspace will be redesigned - see #127 

Resolves #125

### CODE REVIEW

**Comment by psiotwo** [comment]
- The blending-out (or how to call it) is nice (seems planar) for the "Vytvorit pracovni prostor" , while it looks strange for "Editovat pojmy" (it looks like an ex-centric circle)

- workspaceRunInTools localization seems missing

Maybe not related, but when speaking about UX:

- Should not the Request feature & Language combo boxes should be visually consistent (same color (orange) of the button and of the options in the former case, while different (blue x gray) in the latter). The same probably holds for the Advanced button on vocabulary detail

image

**Comment by karelklima** [comment]
> * The blending-out (or how to call it) is nice (seems planar) for the "Vytvorit pracovni prostor" , while it looks strange for "Editovat pojmy" (it looks like an ex-centric circle)

Fixed. Google calls that the ripple effect. It should always start from the center of buttons now.

> * workspaceRunInTools localization seems missing

Fixed, changed to Actions (which makes more sense given the wording of action buttons).

> Maybe not related, but when speaking about UX:
> 
> * Should not the Request feature & Language combo boxes should be visually consistent (same color (orange) of the button and of the options in the former case, while different (blue x gray) in the latter). The same probably holds for the Advanced button on vocabulary detail
> 
> image

The combo boxes / buttons are consistent across the whole app, EXCEPT for the one orange button, and the reason why it's a different color is that people notice that. Eventually we may choose to replace the orange color with something different, I personally consider it as a shortcut for beta-testing purposes. Regarding the orange panel after combo box click - that's an antipattern really, what should happen is that the primary label of the button would be replaced by an option from the combo box, but we are misusing the combobox component a bit for our use case.

**Comment by psiotwo** [comment]
> Fixed. Google calls that the ripple effect. It should always start from the center of buttons now.

Well, it is visually more appealing to me, but now I can see it is weird to me as well as the position is unrelated.

I have no more opinions here. Any suggestion by our Chief Executive Critic @MichalMed?

> The combo boxes / buttons are consistent across the whole app, EXCEPT for the one orange button, and the reason why it's a different color is that people notice that. Eventually we may choose to replace the orange color with something different, I personally consider it as a shortcut for beta-testing purposes. Regarding the orange panel after combo box click - that's an antipattern really, what should happen is that the primary label of the button would be replaced by an option from the combo box, but we are misusing the combobox component a bit for our use case.

Agree. :+1:

**Review by psiotwo — APPROVED** [review]
lgtm
(apart from the super-minor discussion on button effects)

**Comment by karelklima** [comment]
@psiotwo The ripple can be disabled altogether, but it is kind of nice that you get the click feedback.

**Pull request merged**
