### PR TITLE
[#116] Set up standard OIDC authorization flow

### LINKED ISSUE #116: Set up standard OIDC flow with Keycloak
Right now MC uses implicit flow for access token negotiation. It should be refactored to use standard flow.

The user token should be auto-refreshed before expiry.

Related issue / acceptance criteria: https://trello.com/c/7O7Ne17J/317-autorefresh-token%C5%AF-n%C3%A1stroj%C5%AF-vl

### PR DESCRIPTION
**Pull request by karelklima**
Resolves #116 

What's been done:
- switched authorization flow from implicit to code-based so that tokens are not sent in URL
- removed support for secure authorization on Netlify deploy previews as it didn't work anyway because of CORS... the only way to make that work is to change the setup in Keycloak so that it is more open
- silent refresh was already working prior to this PR, should be working still

### CODE REVIEW

**Comment by psiotwo** [comment]
> * silent refresh was already working prior to this PR, should be working still
Not relevant to this PR, but @martinnec experienced an issue before that looked like a problem with the refresh token - after some time of innactivity mission control showed him 500 screen which disappeared after refresh, If I remember correctly.

**Comment by karelklima** [comment]
> Might not be relevant to this PR, but @martinnec experienced an issue yesterday that looked like a problem with the refresh token - after some time of innactivity mission control showed him 500 screen which disappeared after refresh, If I remember correctly.

Thanks for the info. If the browser suspends the tab on background then it could be possible for the access token to expire. The app should fetch a new one, but there may be some race conditions. I'll check it out.

**Comment by karelklima** [comment]
I did some testing, no error. I left MC running in a tab and checked it out half an hour later. The token was refreshed silently (see console log below), I didn't experience any error, the app worked as expected.

Unless we have a console log of the aforementioned error, there is very little I can do about it.

image

**Comment by psiotwo** [comment]
> I did some testing, no error. I left MC running in a tab and checked it out half an hour later. The token was refreshed silently (see console log below), I didn't experience any error, the app worked as expected.
> 
> Unless we have a console log of the aforementioned error, there is very little I can do about it.
> 
> image

OK, now things should work anyway, so a proper ticket will be raised in case the problem reappears.

**Review by psiotwo — COMMENTED** [review]
I changed the expiration timeouts for testing this to 1min in keycloak server. 
While logged in I was on the /vocabularies screen, then - after the token expired - I clicked to open a detail of a workspace, ending up with 500, as shown below.

image

console log:
image


Also it is a bit confusing to claim 500, if all the errors have in fact 4xx status code.

**Comment by karelklima** [comment]
@psiotwo Thanks for the report, I'll check it out. Did you log in to MC and only then changed the Keycloak settings? Because that would explain it.

I guess what we want to do here is that whenever we get a 4xx or 5xx response from the auth server, we should probably just kill the app. There is some error handling already present, but I'll improve it to cover this case as well (will create a separate ticket for that).

The error report - e.g. the wrong number - I took care of that in the other PR.

**Comment by karelklima** [comment]
The two use cases that we need to cover:
1) Request for new access token using refresh token is revoked -> should probably display some message to user and let him log in again
2) Session is terminated on keycloak, or the user has logged out from a different app -> should log him out of MC as well. This is most likely related to use case 1)

**Comment by psiotwo** [comment]
> @psiotwo Thanks for the report, I'll check it out. Did you log in to MC and only then changed the Keycloak settings? Because that would explain it.

Indeed, that's what I did.

**Comment by psiotwo** [comment]
> The two use cases that we need to cover:
> 
> 1. Request for new access token using refresh token is revoked -> should probably display some message to user and let him log in again

> 2. Session is terminated on keycloak, or the user has logged out from a different app -> should log him out of MC as well. This is most likely related to use case 1)
If No-token and Invalid token are handled the same in 1) then probably it should solve 2) as well.

**Comment by karelklima** [comment]
@psiotwo So, after hours of debugging MC I found the problem in Keycloak :-)

image

The issue was that the SSO Session Idle was set to 1 minute for the whole realm, and that in effect is the lifespan of refreshTokens. So what happenned is that when the user logged in, the app got an access token valid for five minutes and a refresh token valid for a only a minute. So if the app tried to renew the access token, Keycloak returned an error, baucase the refresh token was already invalid. I have set the SSO Session Idle back to 30 minutes which is the default value as far as I know.

Just to be sure, I implemented an error handler to force login if silent renewal fails, and also if the session is for some reason expired at the init phase.

With that I consider this issue resolved. Regarding the session termination and log out from other apps - it's not as easy to implement and probably not worth it at the moment, but if we want to do it I'd create a separate ticket for that. Right now if the session is terminated via Keycloak, MC is unable to refresh the tokens which triggers login. But it does not happen right away, only after the refresh request is made.

**Review by psiotwo — APPROVED** [review]
lgtm

**Pull request merged**
