### PR TITLE
[#115] Added issue tracker links

### LINKED ISSUE #115: Add issue tracker link
Description / acceptance criteria: https://trello.com/c/kQHJN6om/318-d%C3%A1t-do-n%C3%A1stroj%C5%AF-odkaz-na-issue-tracker-pro-u%C5%BEivatele

### PR DESCRIPTION
**Pull request by karelklima**
Resolves #115

### CODE REVIEW

**Review by psiotwo — COMMENTED** [review]
Cannot open the deploy preview - should it be working?

**Review by psiotwo — APPROVED** [review]
Had to add preview url explictly to keycloak in order to test it

Works as expected - only the visualization of the secondary action (Request feature) is different (gray normal button) than the main Report bug button (orange) which is strange.

**Comment by karelklima** [comment]
@psiotwo 
> Had to add preview url explictly to keycloak in order to test it

Yes, unfortunately the workaround for deploy previews doesn't really work. The only solution at the moment is to allow origin to Keycloak from `*`.

> Works as expected - only the visualization of the secondary action (Request feature) is different (gray normal button) than the main Report bug button (orange) which is strange.

You're right, fixed!

**Review by psiotwo — APPROVED** [review]
lgtm

**Pull request merged**
